- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  vars:
    zsh_antigen: yes
    vim_vundle: yes
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - python
    - hub
    - tmux
    - git-flow
    - {role: osx, when: ansible_os_family == "Darwin"}
    - {role: i3, when: ansible_os_family == "Debian"}
    - fonts

