# brew bundle install

# Terminal.
brew "autojump"
brew "direnv"
brew "helix"
brew "starship"
cask "firefox"
cask "wezterm"

# Python.
brew "ruff"

# Fonts.
cask "font-ia-writer-duo"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-ia-writer-duospace"
cask "font-monaspace"
