# brew bundle install

# Terminal.
brew "autojump"
brew "direnv"
brew "helix"
brew "starship"
cask "firefox"
brew "fd"
brew "fzf"
cask "wezterm"

# Python.
brew "ruff"

# Fonts.
tap "homebrew/cask-fonts"
cask "font-ia-writer-duo"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-monaspace"
