- name: Create .antigen directory
  file: dest="{{ dotfiles_user_home }}/.antigen" state=directory

- name: Install antigen
  get_url: url=https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh dest="{{ dotfiles_user_home }}/.antigen/antigen.zsh" mode=755

- name: Link antigenrc file
  file: src="{{ dotfiles_home }}/roles/zsh/files/antigenrc.link" dest="{{ dotfiles_user_home }}/.antigenrc" state=link
