[[language]]
name = "python"
language-servers = [ "pylsp" ]
auto-format = true

[language-server.pylsp.config.pylsp]
pyls_flake8.enabled = false
pyls_autopep8.enabled = false
pyls_mccabe.enabled = false
pyls_pycodestyle.enabled = false
pyls_pyflakes.enabled = false
pyls_pylint.enabled = false
pyls_yapf.enabled = false

plugins.pyls_rope.enabled = true
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true
plugins.pyls_black.enabled = true
plugins.pyls_black.live_mode = true
plugins.pyls_ruff.enabled = true
plugins.pyls_ruff.formatEnabled = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer]
command = "rust-analyzer"

