[[language]]
name = "python"
language-servers = [ "pylsp" ]
auto-format = true

[language-server.pylsp.config.pylsp]
pylsp_flake8.enabled = false
pylsp_autopep8.enabled = false
pylsp_mccabe.enabled = false
pylsp_pycodestyle.enabled = false
pylsp_pyflakes.enabled = false
pylsp_pylint.enabled = false
pylsp_yapf.enabled = false

plugins.pylsp_rope.enabled = true
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
plugins.pylsp_black.enabled = true
plugins.pylsp_black.live_mode = true
plugins.pylsp_ruff.enabled = true
plugins.pylsp_ruff.formatEnabled = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer]
command = "rust-analyzer"

